M48
; DRILL file {KiCad 7.0.6} date Tue 15 Aug 2023 19:50:43
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-15T19:50:43+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.1283Y-2.5089
X5.3559Y-2.5089
T2
X5.0423Y-3.1821
T0
M30
